before_install:
# Below is a fix to for `package requires NuGet client version '3.0' or above, but the current NuGet version is '2.12.0.0'.`
# according to https://github.com/travis-ci/travis-ci/issues/5932
# We skip downloading and restoring latest nuget.exe as we have it in our solution
# - mkdir -p .nuget
# - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
#- cd $TRAVIS_BUILD_DIR
- mono .nuget/nuget.exe
install:
- mono .nuget/nuget.exe restore Bridge.NoTest.sln -Verbosity detailed
language: csharp
solution: Bridge.NoTest.sln
before_script:
- npm install -g grunt-cli
- git submodule update --init --recursive
script:
- xbuild /p:Configuration=Release Bridge.NoTest.sln
- mono ./packages/NUnit.ConsoleRunner.*/tools/nunit*-console.exe ./Compiler/TranslatorTests/bin/Release/Bridge.Translator.Tests.dll
cache:
  directories:
  - packages
env:
  global:
  - secure: "IA9c3hmy8ztiUxA7UZ9tC7/TQtZ98alZhHyq0REE5hMWlAQy04bwjebYjyXnIhlUcAK01XMeEy5J1UkDgtxleynx5A06go7GCQ1xE2CT84yCTjbZONDb3+KspQjRL9EBZ/DmQ8ouMLe+0b6vGExzHZL2YWcpJrCKE9fPb6mELnkzxeB25ZExjhEbr/GWblXbzZmv0qaMTkQZoCc1PekTh2Xo5QEtLL6i7I7Z7r2VBD8DJU9eh7f0BuCNMoYQgpkzPk5YtiJVoUVpGEJeAK83gOT6mnMmc3pc6i2yCMK3slwB7uESjnfNhajDEAWOz+MJ0NtRkWNwiFdneHK7CkJnMev/iQP82yIkO6D89K5spPKI8vrxH9GEFNlq4ata4f1JZL+h6iZs962gTIZMuxqujKAgBZld1Frv/b8DATh0OCbOe2fwmlhXXxm8TmfqFH/B0K3rvj/VHIESU9r3M2RJmSOsxct+oKgbtCfPWeZsRqoAvgxfs/HCIh59PbN3ymtZre/lBPqbtp6rBK8ltSYgxgEOlCyKjbHoMjfz2E+j0C60TJ6JBHqq36+wILKSuDXYBAMUIFmH46ojBaBFjvYCUjV4UPmIBteDy46nuZxvciv1fXE1Xw4XqEQFKP5o4X3DUiPQXYnKV4kpAhvlPK9q6hBYW/60aXIxyUwwWr6JBtw="
  - secure: "NS1aARM3r73B0X+JLpsMAhh2hY3krFD19DwS9Hdmtf/kCBZEmQRAODHazToNXcabRiK1pu8EJ8o+s2Mwq4zocZU6XeY6V6CEF+nP3ZT58ky8CShYiubaaiCl/F+UGhjPBefZmBs8U+7dj2L2kXbNr7mVgQ+L+qAUoj/brf3Sro8y1WOv5a7rJ6JK4N7e3gBo0sqh2qlFVq3un6FRTmV0I+m3SeVd7cBixra4csGQCPPmtSvv/OMbeywyKlYqBZkgLh6hQkhMSygnAn+2xAHHCsgda+eCNIRCj6mfwa9Xs7eI/1HE9RJ7MBqizekjXTmsPfWVkhdDGfF38yi3LiM8fxktdx0eS2TgEULAuokq4dGzW6A4gZTjF9jnqS2IYUPfZ0WuZxeFIN/Urhx1cpbFBUtBi2GGySrBsvEWnvEpj6rjfxuIdoff8/9UJpl8xEVXrioNOtnpcs54TbmTtg4ApOA6yVo4P3jvM0xCGqxKRznZYmu/XGmSp/YibXkUuGtFqpMUfKuR0YQr2deXF9kiF3YPb6mJ9h2ezlkhUQOg8hCzPZqKjDDRYmvKW4DVvmQOfJzML+b8KiZxKYtvEC3F2l09ip7w6ydc9c0NHTIDs5C22TVP6OjAAi2MxPK1sbVD93C7ZWR0V6FvcUZVcvngvwqW7M0ILRdmA41ncS7bh1M="
notifications:
  slack:
    secure: Gs/hlDNJYnOk35VqX/VNOKxvj8IyDG2R45rnqLaOb1DMa5DHRa7zkzi4fPCFenPYUFWWKPBfH9OmF75AESoqn9lCMIG2u7r2wTh25G2kBryDpXVd4r+XzWuAQYvJ48HHX7S2+yRVO96ZoPCf0ObFxG8Wq9nF80Hl+CiveKkAXcSznOrDqkCFAXXuq3919PTaxqWdvVSWTKhlD7i8PclBjKciow/O9ie6pwW+PzgNnrhQuHBqWJwauyAEhHZt/AyT1jrBweX9+IGjncE4S25qSQryLBbbCVdNQOZLdYFzn53OgtdSHsFfFYeZceH5epoGYJiMDxXUg+CrbmO5DUQa7HRAYwAMU7XmH1Xu8M+SUi1PctLgqXm0P7qZ5e+xYMQYZipX7xYykyWBPnpMahG9mA09UJ1ezVQHCAzV585qdZ/HZJxGK+3DUzIDpuXJiHpML7fkfx4GZzqTiYLctZEx8oZOsOErOFVJI08nlm3IFg3KTagrPUw5hFHJRWVF3IwhnZ/N28zEMufD+/cTCK6tXcu08KZgY3qGivgi4lHHkXEbkt/ubaH9Kf6GlNjvCDmMELpAm2pDf+3gJTF8MPWmNy6QfkZ2xK9qQWJjui+c8FZOypgEOCUw9ErzFCVxGjHgNwuXn5dcH8JJLYGUoVEf9XM/glyd2M5oxGjl+ITHEcQ=
